@local = http://localhost:8080

@local-Token = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzdXJpeWExMjM0NSIsImlhdCI6MTc4MDI0MzU1NCwiZXhwIjoxNzgwMjQ0MTU0fQ.3cT2hq5Slo-Od9YVmZCFceR2rdkLHRtTUT-_zMQ9930Zmw1gNM-NyLBHixCdomCC56ytc4-rJ8yf7CdSKNFzPg

@token = {{local-Token}}

@baseUrl = {{local}}

###
POST {{baseUrl}}/user/register
Content-Type: application/json

{
    "firstName":"Suriya",
    "lastName":"Prabhu",
    "userName":"suriya12345",
    "email":"suriya1993.je2026@gmail.com",
    "password":"Prabhu@123",
    "phone":"+919566642045",
    "role":"user"
}

###
POST {{baseUrl}}/user/login
Content-Type: application/json

{
    "userNameOrEmailOrPhone":"suriya1993.je2026@gmail.com",
    "password":"Prabhu@123"
}


###
POST {{baseUrl}}/user/verify/otp
Content-Type: application/json

{
    "email":"suriya1993.je2026@gmail.com",
    "otp":"939563"
}

###
GET {{baseUrl}}/user
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/user/refreshKey/a03b78f-ecac-4ec9-a649-7892956566e0
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/forgot/password/suriyasundarrajan340@gmail.com
Content-Type: application/json

###
POST {{baseUrl}}/verify/reset/otp
Content-Type: application/json

{
    "email":"suriyasundarrajan340@gmail.com",
    "otp":"848884"
}

###
POST {{baseUrl}}/change/password
Content-Type: application/json

{
    "email":"suriyasundarrajan340@gmail.com",
    "changedPassword":"Suriya@123"
}

###
GET {{baseUrl}}/user/logout
Content-Type: application/json
Authorization: Bearer {{token}}


 