@local = http://localhost:8080

@local-Token =eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzdXJpeWExMjMiLCJpYXQiOjE3ODUzMDY1OTksImV4cCI6MTc4NTMwNzE5OX0.yytDapA6XujZoveJRKTwDBbGlVLsPIP6b02DDBbY5n3xIp_yooQqTMpYjsysHTSV9iEbMU7fX7VScTmIv8euJw

@token = {{local-Token}}

@baseUrl = {{local}}

###
POST {{baseUrl}}/user-auth/organization/register
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name":"CSI Church",
    "registrationNumber":"45748dCSI",
    "website":"www.csiedmissionchurch.com",
    "address":"14 duthie school junction road near ICICI bank",
    "countryId":100,
    "stateId":21,
    "cityId":497,
    "postalCode":"629002",
    "primaryContactName":"Johnson",
    "primaryContactEmail":"johnson@gmail.com",
    "primaryContactNumber":"7485961236",
    "logoUrl":"",
    "faviconUrl":"",
    "primarycolor":"",
    "timeZone":"",
    "currency":"",
    "language":""
}

###
PUT {{baseUrl}}/user-auth/organization/update/898f51b6-fa6a-4bd3-ae6b-be5db2efbbaf
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name":"CSI Church",
    "address":"14 duthie school junction road near TMB bank",
    "countryId":100,
    "stateId":23,
    "cityId":590,
    "postalCode":"629002",
    "primaryContactName":"JohnsonRaj",
    "primaryContactEmail":"johnson@gmail.com",
    "primaryContactNumber":"7485961236"
}

###
DELETE {{baseUrl}}/user-auth/organization/delete/898f51b6-fa6a-4bd3-ae6b-be5db2efbbaf
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/user-auth/organization
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/user-auth/register
Content-Type: application/json

{
    "organizationId":"e25382f1-4542-4f2e-87be-6b770349de01",
    "firstName":"Anu",
    "lastName":"Ram",
    "userName":"anu123",
    "email":"suriya1993.je2026@gmail.com",
    "contactNumber":"9791652388",
    "gender":"Female",
    "dateOfBirth":"1993-05-22",
    "address":"14 duthie school junction road near TMB bankl",
    "userType":"Super Admin"
}

###
POST {{baseUrl}}/user-auth/email/verification/otp/suriya1993.je2026@gmail.com
Content-Type: application/json

###
POST {{baseUrl}}/user-auth/verify/email/otp
Content-Type: application/json

{
    "email":"suriya1993.je2026@gmail.com",
    "otp":"162389"
}
###
POST {{baseUrl}}/user-auth/login
Content-Type: application/json

{
    "login":"9566642031",
    "password":"Suriya@12345"
}

###
POST {{baseUrl}}/user-auth/verify/otp
Content-Type: application/json

{
    "email":"suriyasundarrajan340@gmail.com",
    "otp":"593329"
}

###
GET {{baseUrl}}/user-auth
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/user-auth/refreshKey/b4b803ac-e021-4b30-b570-cdb8206880ad
Content-Type: application/json

###
POST {{baseUrl}}/user-auth/forgot/password/suriyasundarrajan340@gmail.com
Content-Type: application/json

###
POST {{baseUrl}}/user-auth/verify/reset/otp
Content-Type: application/json

{
    "email":"suriyasundarrajan340@gmail.com",
    "otp":"887306"
}

###
POST {{baseUrl}}/user-auth/change/password
Content-Type: application/json

{
    "resetToken":"75330e81-bbdd-4f92-9e5f-c4ea596afbfa",
    "newPassword":"Suriya@12345",
    "confirmPassword":"Suriya@12345"
}

###
POST {{baseUrl}}/user-auth/signout
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/user-auth/location/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "location":"Nagercoil",
    "description":"kjhknlsfldlfm"
}

###
PUT {{baseUrl}}/user-auth/location/update/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "location":"Nagercoil",
    "description":"sdfdfddf"
}

###
DELETE {{baseUrl}}/user-auth/location/delete/1
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/user-auth/location
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/user-auth/member/category/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "category":"Believer",
    "description":"sdfdsfhghjfgsfef"
}

###
PUT {{baseUrl}}/user-auth/member/category/update/id/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "category":"Believer",
    "description":"fdssfdfdsfdf"
}

###
DELETE {{baseUrl}}/user-auth/member/category/delete/id/1
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/user-auth/member/category/
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/user-auth/member/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "organizationId":"f0768d32-efd3-4d5e-84f4-1159af6617bf",
    "organizationCode":"CH_00001",
    "familyHeadId":"",
    "category":"sdfdsfhghjfgsfef",
    "location":"kanyakumari",
    "relationShip":"",
    "firstName":"Yuva",
    "lastName":"Raj",
    "userName":"yuva212345",
    "gender":"Male",
    "dateOfBirth":"2025-10-05",
    "dateOfJoin":"2025-05-10",
    "weddingDate":"",
    "email":"yuva@gmail.com",
    "contactNumber":"+919578642314",
    "address":"No 6 RGV colony ljdlflfmkjkdf nagercoil kanya kumari district",
    "isWaterBaptised":true,
    "isSpiritBaptised":false
}

###
PUT {{baseUrl}}/user-auth/member/update/af8e447b-79b4-4002-adc3-d8c8d68df791
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "organizationId":"c3688ba9-b256-48fa-84ba-c0a6f6a8bc9c",
    "organizationCode":"CH_00010",
    "familyHeadId":"",
    "category":"Believer",
    "location":"Nagercoil",
    "relationShip":"Father",
    "firstName":"Michael",
    "lastName":"John",
    "userName":"michael123",
    "gender":"Male",
    "dateOfBirth":"2027-05-08",
    "dateOfJoin":"2025-10-18",
    "weddingDate":"",
    "email":"michael@gmail.com",
    "contactNumber":"9741526398",
    "address":"No 6 ngm colony ljdlflfmkjkdf nagercoil kanya kumari district",
    "isWaterBaptised":true,
    "isSpiritBaptised":false

}

###
DELETE {{baseUrl}}/user-auth/member/delete/
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/user-auth/country/
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/user-auth/states/
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/user-auth/states/100
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/user-auth/city
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/user-auth/city/1
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/user-auth/subscription/plan
Content-Type: application/json

###
GET {{baseUrl}}/user-auth/subscription/feature
Content-Type: application/json

