@local = http://localhost:8080

@local-Token = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzdXJpeWExMjMiLCJpYXQiOjE3ODcyMTY5ODEsImV4cCI6MTc4NzIxNzU4MX0.xPdsU8PpgjY3Mjh-KRYeR38sy9AolQByPzTMMyEy3RUKQxdfD42BEg6u1zMXX_F9f1MZu6f5lwRatVT9ow2hwg

@token = {{local-Token}}

@baseUrl = {{local}}


###
POST {{baseUrl}}/api/auth/v1/user/login
Content-Type: application/json

{
    "login":"9566642031",
    "password":"Suriya@12345"
}

###
POST {{baseUrl}}/api/auth/v1/user/verify/otp
Content-Type: application/json

{
    "email":"suriyasundarrajan340@gmail.com",
    "otp":"407677"
}

###
POST {{baseUrl}}/api/v1/user/refreshKey/038c8f94-144d-4d2d-9415-1405443d68b8
Content-Type: application/json

###
POST {{baseUrl}}/api/v1/access/control/role/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "roleName":"AdminRole",
    "description":"adfdkjufdfhhfdf"
}

###
PUT {{baseUrl}}/api/v1/access/control/role/update/f84066a3-b940-40e3-8431-146a62ad0788
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "roleName":"Admin",
    "description":"lkjslfkjdskjfkdmdfg"
}

###
DELETE {{baseUrl}}/api/v1/access/control/role/delete/f84066a3-b940-40e3-8431-146a62ad0788
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET {{baseUrl}}/api/v1/access/control/role
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/api/v1/access/control/route/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "controllerName":"User Controller",
    "backendRoute":"/api/v1/auth/user/login",
    "frontendRoute":"",
    "description":"user login page 632",
    "isDefault":""
}

###
PUT {{baseUrl}}/api/v1/access/control/route/update/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "controllerName":"UserController",
    "backendRoute":"/api/v1/auth/user/login",
    "frontendRoute":"",
    "description":"user login page",
    "isDefault":""
}

###
DELETE {{baseUrl}}/api/v1/access/control/route/delete/1
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET {{baseUrl}}/api/v1/access/control/route
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/api/v1/access/control/module/preset/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "moduleName":"User-Module",
    "presetName":"ViewOnly",
    "description":"user module view only"
}

###
PUT {{baseUrl}}/api/v1/access/control/module/preset/update/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "moduleName":"UserModule",
    "presetName":"viewOnly",
    "description":"sfjowejrlkme"
}

###
DELETE {{baseUrl}}/api/v1/access/control/module/preset/delete/1
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET {{baseUrl}}/api/v1/access/control/module/preset
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/api/v1/access/control/route/preset/access/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "modulePresetId":1,
    "routeId":1
}

###
PUT {{baseUrl}}/api/v1/access/control/route/preset/access/update/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "modulePresetId":"",
    "routeId":""
}

###
DELETE {{baseUrl}}/api/v1/access/control/route/preset/access/delete/
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET {{baseUrl}}/api/v1/access/control/route/preset/access
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/api/v1/access/control/role/preset/access/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "roleId":"f84066a3-b940-40e3-8431-146a62ad0788",
    "modulePresetId":1
}

###
PUT {{baseUrl}}/api/v1/access/control/role/preset/access/update/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "modulePresetId":"",
    "routeId":""
}

###
DELETE {{baseUrl}}/api/v1/access/control/role/preset/access/delete/
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET {{baseUrl}}/api/v1/access/control/role/preset/access
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/api/v1/access/control/user/role/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "userId":"3959b18c-6d33-41f9-96c1-e9c32b2631f5",
    "roleId":"f84066a3-b940-40e3-8431-146a62ad0788"
}

###
PUT {{baseUrl}}/api/v1/access/control/user/role/update/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "userId":"gjhj",
    "roleId":"hgjhj"
}

###
DELETE {{baseUrl}}/api/v1/access/control/user/role/delete/1
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET {{baseUrl}}/api/v1/access/control/user/role
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/api/v1/sunday/school/class/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "organizationId":"6817486e-f4ab-4830-bb12-3e29e302e4ed",
    "className":"Intermediate",
    "classNumber":2
}

###
GET {{baseUrl}}/api/v1/sunday/school/class
Content-Type: application/json
Authorization: Bearer {{token}}

###
PUT {{baseUrl}}/api/v1/sunday/school/class/update/940ffdfe-9312-42ab-83e8-7ada1e02edfa
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "className":"Beginners",
    "classNumber":1
}

###
DELETE {{baseUrl}}/api/v1/sunday/school/class/delete/
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/api/v1/sunday/school/teacher/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "organizationId":"6817486e-f4ab-4830-bb12-3e29e302e4ed",
    "memberId":"d6ea1bd4-c452-4543-91b0-0a70cd30abfc",
    "classId":"940ffdfe-9312-42ab-83e8-7ada1e02edfa",
    "dateOfJoin":"2026-08-19"
}

###
GET {{baseUrl}}/api/v1/sunday/school/teacher
Content-Type: application/json
Authorization: Bearer {{token}}

###
PUT {{baseUrl}}/api/v1/sunday/school/teacher/update/940ffdfe-9312-42ab-83e8-7ada1e02edfa
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "classId":"940ffdfe-9312-42ab-83e8-7ada1e02edfa",
    "dateOfJoin":1
}

###
DELETE {{baseUrl}}/api/v1/sunday/school/teacher/delete/940ffdfe-9312-42ab-83e8-7ada1e02edfa
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/api/v1/sunday/school/student/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "organizationId":"6817486e-f4ab-4830-bb12-3e29e302e4ed",
    "memberId":"d6ea1bd4-c452-4543-91b0-0a70cd30abfc",
    "name":"",
    "gender":"female",
    "age":20,
    "dateOfBirth":"2000-10-12",
    "classId":"940ffdfe-9312-42ab-83e8-7ada1e02edfa",
    "teacherId":""
}

###
GET {{baseUrl}}/api/v1/sunday/school/student
Content-Type: application/json
Authorization: Bearer {{token}}

###
PUT {{baseUrl}}/api/v1/sunday/school/student/update/0097da42-d362-4bb0-a4d4-8ff12287b43f
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name":"Aarthi",
    "age":20,
    "dateOfBirth":"2000-10-12",
    "classId":"940ffdfe-9312-42ab-83e8-7ada1e02edfa"
}

###
DELETE {{baseUrl}}/api/v1/sunday/school/student/delete/1
Content-Type: application/json
Authorization: Bearer {{token}}


###
POST {{baseUrl}}/api/v1/sunday/school/attendance/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "organizationId":"6817486e-f4ab-4830-bb12-3e29e302e4ed",
    "attendanceDate":"2026-08-20",
    "attendanceList":[
        {
            "studentId":"0097da42-d362-4bb0-a4d4-8ff12287b43f",
            "attendanceStatus":"PRESENT"
        },
        {
            "studentId":"d49f4200-5190-48f1-83f8-4a839f75345a",
            "attendanceStatus":"ABSENT"
        }
    ]
}

###
GET {{baseUrl}}/api/v1/sunday/school/attendance
Content-Type: application/json
Authorization: Bearer {{token}}

###
PUT {{baseUrl}}/api/v1/sunday/school/attendance/update
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "organizationId":"6817486e-f4ab-4830-bb12-3e29e302e4ed",
    "studentId":"d49f4200-5190-48f1-83f8-4a839f75345a",
    "attendanceDate":"2026-08-20",
    "attendanceStatus":"PRESET"
}

###
DELETE {{baseUrl}}/api/v1/sunday/school/attendance/delete/3a13bb2c-c0f9-4ed9-8005-64ceea56a114
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/api/v1/sunday/school/transition/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "studentId":"0097da42-d362-4bb0-a4d4-8ff12287b43f",
    "fromClassId":"940ffdfe-9312-42ab-83e8-7ada1e02edfa",
    "toClassId":"8c67ab1a-784c-4b6f-bd2e-7b214cc3a00b",
    "transitionBy":"fb8fddc5-2567-41c5-bf7b-60d9c54ea1d9",
    "transitionDate":"2026-08-20"
}

###
GET {{baseUrl}}/api/v1/sunday/school/transition
Content-Type: application/json
Authorization: Bearer {{token}}

###
PUT {{baseUrl}}/api/v1/sunday/school/transition/update/a4f97106-7580-452b-9347-541cda3fc4e9
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "studentId":"0097da42-d362-4bb0-a4d4-8ff12287b43f",
    "fromClassId":"8c67ab1a-784c-4b6f-bd2e-7b214cc3a00b",
    "toClassId":"940ffdfe-9312-42ab-83e8-7ada1e02edfa",
    "transitionBy":"fb8fddc5-2567-41c5-bf7b-60d9c54ea1d9",
    "transitionDate":"2026-08-20"
}

###
DELETE {{baseUrl}}/api/v1/sunday/school/transition/delete/a4f97106-7580-452b-9347-541cda3fc4e9
Content-Type: application/json
Authorization: Bearer {{token}}







