CREATE TABLE master_countries (
    id SERIAL PRIMARY KEY,
    country_code CHAR(2),
    iso3 CHAR(3),
    country_name VARCHAR(80) NOT NULL,
    num_code SMALLINT,
    sort_order INTEGER
);
CREATE TABLE master_states (
    id SERIAL PRIMARY KEY,
    country_id INTEGER,
    country_code CHAR(4),
    state_code CHAR(4) NOT NULL,
    state_name VARCHAR(100) NOT NULL
);
CREATE TABLE master_cities (
    id SERIAL PRIMARY KEY,
    country_code CHAR(4),
    state_id INTEGER,
    city VARCHAR(255) NOT NULL
);
INSERT INTO master_countries (
        id,
        country_code,
        iso3,
        country_name,
        num_code,
        sort_order
    )
VALUES (1, 'US', NULL, 'United States', NULL, NULL),
    (2, 'CA', NULL, 'Canada', NULL, NULL),
    (3, 'AF', NULL, 'Afghanistan', NULL, NULL),
    (4, 'AL', NULL, 'Albania', NULL, NULL),
    (5, 'DZ', NULL, 'Algeria', NULL, NULL),
    (6, 'AS', NULL, 'American Samoa', NULL, NULL),
    (7, 'AD', NULL, 'Andorra', NULL, NULL),
    (8, 'AO', NULL, 'Angola', NULL, NULL),
    (9, 'AI', NULL, 'Anguilla', NULL, NULL),
    (10, 'AQ', NULL, 'Antarctica', NULL, NULL),
    (
        11,
        'AG',
        NULL,
        'Antigua and/or Barbuda',
        NULL,
        NULL
    ),
    (12, 'AR', NULL, 'Argentina', NULL, NULL),
    (13, 'AM', NULL, 'Armenia', NULL, NULL),
    (14, 'AW', NULL, 'Aruba', NULL, NULL),
    (15, 'AU', NULL, 'Australia', NULL, NULL),
    (16, 'AT', NULL, 'Austria', NULL, NULL),
    (17, 'AZ', NULL, 'Azerbaijan', NULL, NULL),
    (18, 'BS', NULL, 'Bahamas', NULL, NULL),
    (19, 'BH', NULL, 'Bahrain', NULL, NULL),
    (20, 'BD', NULL, 'Bangladesh', NULL, NULL),
    (21, 'BB', NULL, 'Barbados', NULL, NULL),
    (22, 'BY', NULL, 'Belarus', NULL, NULL),
    (23, 'BE', NULL, 'Belgium', NULL, NULL),
    (24, 'BZ', NULL, 'Belize', NULL, NULL),
    (25, 'BJ', NULL, 'Benin', NULL, NULL),
    (26, 'BM', NULL, 'Bermuda', NULL, NULL),
    (27, 'BT', NULL, 'Bhutan', NULL, NULL),
    (28, 'BO', NULL, 'Bolivia', NULL, NULL),
    (
        29,
        'BA',
        NULL,
        'Bosnia and Herzegovina',
        NULL,
        NULL
    ),
    (30, 'BW', NULL, 'Botswana', NULL, NULL),
    (31, 'BV', NULL, 'Bouvet Island', NULL, NULL),
    (32, 'BR', NULL, 'Brazil', NULL, NULL),
    (
        33,
        'IO',
        NULL,
        'British lndian Ocean Territory',
        NULL,
        NULL
    ),
    (34, 'BN', NULL, 'Brunei Darussalam', NULL, NULL),
    (35, 'BG', NULL, 'Bulgaria', NULL, NULL),
    (36, 'BF', NULL, 'Burkina Faso', NULL, NULL),
    (37, 'BI', NULL, 'Burundi', NULL, NULL),
    (38, 'KH', NULL, 'Cambodia', NULL, NULL),
    (39, 'CM', NULL, 'Cameroon', NULL, NULL),
    (40, 'CV', NULL, 'Cape Verde', NULL, NULL),
    (41, 'KY', NULL, 'Cayman Islands', NULL, NULL),
    (
        42,
        'CF',
        NULL,
        'Central African Republic',
        NULL,
        NULL
    ),
    (43, 'TD', NULL, 'Chad', NULL, NULL),
    (44, 'CL', NULL, 'Chile', NULL, NULL),
    (45, 'CN', NULL, 'China', NULL, NULL),
    (46, 'CX', NULL, 'Christmas Island', NULL, NULL),
    (
        47,
        'CC',
        NULL,
        'Cocos (Keeling) Islands',
        NULL,
        NULL
    ),
    (48, 'CO', NULL, 'Colombia', NULL, NULL),
    (49, 'KM', NULL, 'Comoros', NULL, NULL),
    (50, 'CG', NULL, 'Congo', NULL, NULL),
    (51, 'CK', NULL, 'Cook Islands', NULL, NULL),
    (52, 'CR', NULL, 'Costa Rica', NULL, NULL),
    (53, 'HR', NULL, 'Croatia (Hrvatska)', NULL, NULL),
    (54, 'CU', NULL, 'Cuba', NULL, NULL),
    (55, 'CY', NULL, 'Cyprus', NULL, NULL),
    (56, 'CZ', NULL, 'Czech Republic', NULL, NULL),
    (
        57,
        'CD',
        NULL,
        'Democratic Republic of Congo',
        NULL,
        NULL
    ),
    (58, 'DK', NULL, 'Denmark', NULL, NULL),
    (59, 'DJ', NULL, 'Djibouti', NULL, NULL),
    (60, 'DM', NULL, 'Dominica', NULL, NULL),
    (61, 'DO', NULL, 'Dominican Republic', NULL, NULL),
    (62, 'TP', NULL, 'East Timor', NULL, NULL),
    (63, 'EC', NULL, 'Ecudaor', NULL, NULL),
    (64, 'EG', NULL, 'Egypt', NULL, NULL),
    (65, 'SV', NULL, 'El Salvador', NULL, NULL),
    (66, 'GQ', NULL, 'Equatorial Guinea', NULL, NULL),
    (67, 'ER', NULL, 'Eritrea', NULL, NULL),
    (68, 'EE', NULL, 'Estonia', NULL, NULL),
    (69, 'ET', NULL, 'Ethiopia', NULL, NULL),
    (
        70,
        'FK',
        NULL,
        'Falkland Islands (Malvinas)',
        NULL,
        NULL
    ),
    (71, 'FO', NULL, 'Faroe Islands', NULL, NULL),
    (72, 'FJ', NULL, 'Fiji', NULL, NULL),
    (73, 'FI', NULL, 'Finland', NULL, NULL),
    (74, 'FR', NULL, 'France', NULL, NULL),
    (
        75,
        'FX',
        NULL,
        'France, Metropolitan',
        NULL,
        NULL
    ),
    (76, 'GF', NULL, 'French Guiana', NULL, NULL),
    (77, 'PF', NULL, 'French Polynesia', NULL, NULL),
    (
        78,
        'TF',
        NULL,
        'French Southern Territories',
        NULL,
        NULL
    ),
    (79, 'GA', NULL, 'Gabon', NULL, NULL),
    (80, 'GM', NULL, 'Gambia', NULL, NULL),
    (81, 'GE', NULL, 'Georgia', NULL, NULL),
    (82, 'DE', NULL, 'Germany', NULL, NULL),
    (83, 'GH', NULL, 'Ghana', NULL, NULL),
    (84, 'GI', NULL, 'Gibraltar', NULL, NULL),
    (85, 'GR', NULL, 'Greece', NULL, NULL),
    (86, 'GL', NULL, 'Greenland', NULL, NULL),
    (87, 'GD', NULL, 'Grenada', NULL, NULL),
    (88, 'GP', NULL, 'Guadeloupe', NULL, NULL),
    (89, 'GU', NULL, 'Guam', NULL, NULL),
    (90, 'GT', NULL, 'Guatemala', NULL, NULL),
    (91, 'GN', NULL, 'Guinea', NULL, NULL),
    (92, 'GW', NULL, 'Guinea-Bissau', NULL, NULL),
    (93, 'GY', NULL, 'Guyana', NULL, NULL),
    (94, 'HT', NULL, 'Haiti', NULL, NULL),
    (
        95,
        'HM',
        NULL,
        'Heard and Mc Donald Islands',
        NULL,
        NULL
    ),
    (96, 'HN', NULL, 'Honduras', NULL, NULL),
    (97, 'HK', NULL, 'Hong Kong', NULL, NULL),
    (98, 'HU', NULL, 'Hungary', NULL, NULL),
    (99, 'IS', NULL, 'Iceland', NULL, NULL),
    (100, 'IN', NULL, 'India', NULL, NULL),
    (101, 'ID', NULL, 'Indonesia', NULL, NULL),
    (
        102,
        'IR',
        NULL,
        'Iran (Islamic Republic of)',
        NULL,
        NULL
    ),
    (103, 'IQ', NULL, 'Iraq', NULL, NULL),
    (104, 'IE', NULL, 'Ireland', NULL, NULL),
    (105, 'IL', NULL, 'Israel', NULL, NULL),
    (106, 'IT', NULL, 'Italy', NULL, NULL),
    (107, 'CI', NULL, 'Ivory Coast', NULL, NULL),
    (108, 'JM', NULL, 'Jamaica', NULL, NULL),
    (109, 'JP', NULL, 'Japan', NULL, NULL),
    (110, 'JO', NULL, 'Jordan', NULL, NULL),
    (111, 'KZ', NULL, 'Kazakhstan', NULL, NULL),
    (112, 'KE', NULL, 'Kenya', NULL, NULL),
    (113, 'KI', NULL, 'Kiribati', NULL, NULL),
    (
        114,
        'KP',
        NULL,
        'Korea, Democratic People''s Republic of',
        NULL,
        NULL
    ),
    (
        115,
        'KR',
        NULL,
        'Korea, Republic of',
        NULL,
        NULL
    ),
    (116, 'KW', NULL, 'Kuwait', NULL, NULL),
    (117, 'KG', NULL, 'Kyrgyzstan', NULL, NULL),
    (
        118,
        'LA',
        NULL,
        'Lao People''s Democratic Republic',
        NULL,
        NULL
    ),
    (119, 'LV', NULL, 'Latvia', NULL, NULL),
    (120, 'LB', NULL, 'Lebanon', NULL, NULL),
    (121, 'LS', NULL, 'Lesotho', NULL, NULL),
    (122, 'LR', NULL, 'Liberia', NULL, NULL),
    (
        123,
        'LY',
        NULL,
        'Libyan Arab Jamahiriya',
        NULL,
        NULL
    ),
    (124, 'LI', NULL, 'Liechtenstein', NULL, NULL),
    (125, 'LT', NULL, 'Lithuania', NULL, NULL),
    (126, 'LU', NULL, 'Luxembourg', NULL, NULL),
    (127, 'MO', NULL, 'Macau', NULL, NULL),
    (128, 'MK', NULL, 'Macedonia', NULL, NULL),
    (129, 'MG', NULL, 'Madagascar', NULL, NULL),
    (130, 'MW', NULL, 'Malawi', NULL, NULL),
    (131, 'MY', NULL, 'Malaysia', NULL, NULL),
    (132, 'MV', NULL, 'Maldives', NULL, NULL),
    (133, 'ML', NULL, 'Mali', NULL, NULL),
    (134, 'MT', NULL, 'Malta', NULL, NULL),
    (135, 'MH', NULL, 'Marshall Islands', NULL, NULL),
    (136, 'MQ', NULL, 'Martinique', NULL, NULL),
    (137, 'MR', NULL, 'Mauritania', NULL, NULL),
    (138, 'MU', NULL, 'Mauritius', NULL, NULL),
    (139, 'TY', NULL, 'Mayotte', NULL, NULL),
    (140, 'MX', NULL, 'Mexico', NULL, NULL),
    (
        141,
        'FM',
        NULL,
        'Micronesia, Federated States of',
        NULL,
        NULL
    ),
    (
        142,
        'MD',
        NULL,
        'Moldova, Republic of',
        NULL,
        NULL
    ),
    (143, 'MC', NULL, 'Monaco', NULL, NULL),
    (144, 'MN', NULL, 'Mongolia', NULL, NULL),
    (145, 'MS', NULL, 'Montserrat', NULL, NULL),
    (146, 'MA', NULL, 'Morocco', NULL, NULL),
    (147, 'MZ', NULL, 'Mozambique', NULL, NULL),
    (148, 'MM', NULL, 'Myanmar', NULL, NULL),
    (149, 'NA', NULL, 'Namibia', NULL, NULL),
    (150, 'NR', NULL, 'Nauru', NULL, NULL),
    (151, 'NP', NULL, 'Nepal', NULL, NULL),
    (152, 'NL', NULL, 'Netherlands', NULL, NULL),
    (
        153,
        'AN',
        NULL,
        'Netherlands Antilles',
        NULL,
        NULL
    ),
    (154, 'NC', NULL, 'New Caledonia', NULL, NULL),
    (155, 'NZ', NULL, 'New Zealand', NULL, NULL),
    (156, 'NI', NULL, 'Nicaragua', NULL, NULL),
    (157, 'NE', NULL, 'Niger', NULL, NULL),
    (158, 'NG', NULL, 'Nigeria', NULL, NULL),
    (159, 'NU', NULL, 'Niue', NULL, NULL),
    (160, 'NF', NULL, 'Norfork Island', NULL, NULL),
    (
        161,
        'MP',
        NULL,
        'Northern Mariana Islands',
        NULL,
        NULL
    ),
    (162, 'NO', NULL, 'Norway', NULL, NULL),
    (163, 'OM', NULL, 'Oman', NULL, NULL),
    (164, 'PK', NULL, 'Pakistan', NULL, NULL),
    (165, 'PW', NULL, 'Palau', NULL, NULL),
    (166, 'PA', NULL, 'Panama', NULL, NULL),
    (167, 'PG', NULL, 'Papua New Guinea', NULL, NULL),
    (168, 'PY', NULL, 'Paraguay', NULL, NULL),
    (169, 'PE', NULL, 'Peru', NULL, NULL),
    (170, 'PH', NULL, 'Philippines', NULL, NULL),
    (171, 'PN', NULL, 'Pitcairn', NULL, NULL),
    (172, 'PL', NULL, 'Poland', NULL, NULL),
    (173, 'PT', NULL, 'Portugal', NULL, NULL),
    (174, 'PR', NULL, 'Puerto Rico', NULL, NULL),
    (175, 'QA', NULL, 'Qatar', NULL, NULL),
    (
        176,
        'SS',
        NULL,
        'Republic of South Sudan',
        NULL,
        NULL
    ),
    (177, 'RE', NULL, 'Reunion', NULL, NULL),
    (178, 'RO', NULL, 'Romania', NULL, NULL),
    (
        179,
        'RU',
        NULL,
        'Russian Federation',
        NULL,
        NULL
    ),
    (180, 'RW', NULL, 'Rwanda', NULL, NULL),
    (
        181,
        'KN',
        NULL,
        'Saint Kitts and Nevis',
        NULL,
        NULL
    ),
    (182, 'LC', NULL, 'Saint Lucia', NULL, NULL),
    (
        183,
        'VC',
        NULL,
        'Saint Vincent and the Grenadines',
        NULL,
        NULL
    ),
    (184, 'WS', NULL, 'Samoa', NULL, NULL),
    (185, 'SM', NULL, 'San Marino', NULL, NULL),
    (
        186,
        'ST',
        NULL,
        'Sao Tome and Principe',
        NULL,
        NULL
    ),
    (187, 'SA', NULL, 'Saudi Arabia', NULL, NULL),
    (188, 'SN', NULL, 'Senegal', NULL, NULL),
    (189, 'RS', NULL, 'Serbia', NULL, NULL),
    (190, 'SC', NULL, 'Seychelles', NULL, NULL),
    (191, 'SL', NULL, 'Sierra Leone', NULL, NULL),
    (192, 'SG', NULL, 'Singapore', NULL, NULL),
    (193, 'SK', NULL, 'Slovakia', NULL, NULL),
    (194, 'SI', NULL, 'Slovenia', NULL, NULL),
    (195, 'SB', NULL, 'Solomon Islands', NULL, NULL),
    (196, 'SO', NULL, 'Somalia', NULL, NULL),
    (197, 'ZA', NULL, 'South Africa', NULL, NULL),
    (
        198,
        'GS',
        NULL,
        'South Georgia South Sandwich Islands',
        NULL,
        NULL
    ),
    (199, 'ES', NULL, 'Spain', NULL, NULL),
    (200, 'LK', NULL, 'Sri Lanka', NULL, NULL),
    (201, 'SH', NULL, 'St. Helena', NULL, NULL),
    (
        202,
        'PM',
        NULL,
        'St. Pierre and Miquelon',
        NULL,
        NULL
    ),
    (203, 'SD', NULL, 'Sudan', NULL, NULL),
    (204, 'SR', NULL, 'Suriname', NULL, NULL),
    (
        205,
        'SJ',
        NULL,
        'Svalbarn and Jan Mayen Islands',
        NULL,
        NULL
    ),
    (206, 'SZ', NULL, 'Swaziland', NULL, NULL),
    (207, 'SE', NULL, 'Sweden', NULL, NULL),
    (208, 'CH', NULL, 'Switzerland', NULL, NULL),
    (
        209,
        'SY',
        NULL,
        'Syrian Arab Republic',
        NULL,
        NULL
    ),
    (210, 'TW', NULL, 'Taiwan', NULL, NULL),
    (211, 'TJ', NULL, 'Tajikistan', NULL, NULL),
    (
        212,
        'TZ',
        NULL,
        'Tanzania, United Republic of',
        NULL,
        NULL
    ),
    (213, 'TH', NULL, 'Thailand', NULL, NULL),
    (214, 'TG', NULL, 'Togo', NULL, NULL),
    (215, 'TK', NULL, 'Tokelau', NULL, NULL),
    (216, 'TO', NULL, 'Tonga', NULL, NULL),
    (
        217,
        'TT',
        NULL,
        'Trinidad and Tobago',
        NULL,
        NULL
    ),
    (218, 'TN', NULL, 'Tunisia', NULL, NULL),
    (219, 'TR', NULL, 'Turkey', NULL, NULL),
    (220, 'TM', NULL, 'Turkmenistan', NULL, NULL),
    (
        221,
        'TC',
        NULL,
        'Turks and Caicos Islands',
        NULL,
        NULL
    ),
    (222, 'TV', NULL, 'Tuvalu', NULL, NULL),
    (223, 'UG', NULL, 'Uganda', NULL, NULL),
    (224, 'UA', NULL, 'Ukraine', NULL, NULL),
    (
        225,
        'AE',
        NULL,
        'United Arab Emirates',
        NULL,
        NULL
    ),
    (226, 'GB', NULL, 'United Kingdom', NULL, NULL),
    (
        227,
        'UM',
        NULL,
        'United States minor outlying islands',
        NULL,
        NULL
    ),
    (228, 'UY', NULL, 'Uruguay', NULL, NULL),
    (229, 'UZ', NULL, 'Uzbekistan', NULL, NULL),
    (230, 'VU', NULL, 'Vanuatu', NULL, NULL),
    (
        231,
        'VA',
        NULL,
        'Vatican City State',
        NULL,
        NULL
    ),
    (232, 'VE', NULL, 'Venezuela', NULL, NULL),
    (233, 'VN', NULL, 'Vietnam', NULL, NULL),
    (
        234,
        'VG',
        NULL,
        'Virgin Islands (British)',
        NULL,
        NULL
    ),
    (
        235,
        'VI',
        NULL,
        'Virgin Islands (U.S.)',
        NULL,
        NULL
    ),
    (
        236,
        'WF',
        NULL,
        'Wallis and Futuna Islands',
        NULL,
        NULL
    ),
    (237, 'EH', NULL, 'Western Sahara', NULL, NULL),
    (238, 'YE', NULL, 'Yemen', NULL, NULL),
    (239, 'YU', NULL, 'Yugoslavia', NULL, NULL),
    (240, 'ZR', NULL, 'Zaire', NULL, NULL),
    (241, 'ZM', NULL, 'Zambia', NULL, NULL),
    (242, 'ZW', NULL, 'Zimbabwe', NULL, NULL);
INSERT INTO master_states (
        id,
        country_id,
        country_code,
        state_code,
        state_name
    )
VALUES (1, 1, 'US', 'AK', 'Alaska'),
    (2, 1, 'US', 'AL', 'Alabama'),
    (3, 1, 'US', 'AR', 'Arkansas'),
    (4, 1, 'US', 'AZ', 'Arizona'),
    (5, 1, 'US', 'CA', 'California'),
    (6, 1, 'US', 'CO', 'Colorado'),
    (7, 1, 'US', 'CT', 'Connecticut'),
    (8, 1, 'US', 'DC', 'District of Columbia'),
    (9, 1, 'US', 'DE', 'Delaware'),
    (10, 1, 'US', 'FL', 'Florida'),
    (11, 1, 'US', 'GA', 'Georgia'),
    (12, 1, 'US', 'HI', 'Hawaii'),
    (13, 1, 'US', 'IA', 'Iowa'),
    (14, 1, 'US', 'ID', 'Idaho'),
    (15, 1, 'US', 'IL', 'Illinois'),
    (16, 1, 'US', 'IN', 'Indiana'),
    (17, 1, 'US', 'KS', 'Kansas'),
    (18, 1, 'US', 'KY', 'Kentucky'),
    (19, 1, 'US', 'LA', 'Louisiana'),
    (20, 1, 'US', 'MA', 'Massachusetts'),
    (21, 1, 'US', 'MD', 'Maryland'),
    (22, 1, 'US', 'ME', 'Maine'),
    (23, 1, 'US', 'MI', 'Michigan'),
    (24, 1, 'US', 'MN', 'Minnesota'),
    (25, 1, 'US', 'MO', 'Missouri'),
    (26, 1, 'US', 'MS', 'Mississippi'),
    (27, 1, 'US', 'MT', 'Montana'),
    (28, 1, 'US', 'NC', 'North Carolina'),
    (29, 1, 'US', 'ND', 'North Dakota'),
    (30, 1, 'US', 'NE', 'Nebraska'),
    (31, 1, 'US', 'NH', 'New Hampshire'),
    (32, 1, 'US', 'NJ', 'New Jersey'),
    (33, 1, 'US', 'NM', 'New Mexico'),
    (34, 1, 'US', 'NV', 'Nevada'),
    (35, 1, 'US', 'NY', 'New York'),
    (36, 1, 'US', 'OH', 'Ohio'),
    (37, 1, 'US', 'OK', 'Oklahoma'),
    (38, 1, 'US', 'OR', 'Oregon'),
    (39, 1, 'US', 'PA', 'Pennsylvania'),
    (40, 1, 'US', 'RI', 'Rhode Island'),
    (41, 1, 'US', 'SC', 'South Carolina'),
    (42, 1, 'US', 'SD', 'South Dakota'),
    (43, 1, 'US', 'TN', 'Tennessee'),
    (44, 1, 'US', 'TX', 'Texas'),
    (45, 1, 'US', 'UT', 'Utah'),
    (46, 1, 'US', 'VA', 'Virginia'),
    (47, 1, 'US', 'VT', 'Vermont'),
    (48, 1, 'US', 'WA', 'Washington'),
    (49, 1, 'US', 'WI', 'Wisconsin'),
    (50, 1, 'US', 'WV', 'West Virginia'),
    (51, 1, 'US', 'WY', 'Wyoming'),
    (52, 100, 'IN', 'AN', 'ANDAMAN & NICOBAR'),
    (53, 100, 'IN', 'AP', 'ANDHRA PRADESH'),
    (54, 100, 'IN', 'AR', 'ARUNACHAL PRADESH'),
    (55, 100, 'IN', 'AM', 'ASSAM'),
    (56, 100, 'IN', 'BR', 'BIHAR'),
    (57, 100, 'IN', 'CH', 'CHANDIGARH'),
    (58, 100, 'IN', 'CR', 'CHATTISGARH'),
    (59, 100, 'IN', 'DN', 'DADRA & NAGAR'),
    (60, 100, 'IN', 'DD', 'DAMAN & DIU'),
    (61, 100, 'IN', 'DL', 'DELHI'),
    (62, 100, 'IN', 'GA', 'GOA'),
    (63, 100, 'IN', 'GU', 'GUJRAT'),
    (64, 100, 'IN', 'HR', 'HARYANA'),
    (65, 100, 'IN', 'HP', 'HIMACHAL PRADESH'),
    (66, 100, 'IN', 'JK', 'JAMMU & KASHMIR'),
    (67, 100, 'IN', 'JR', 'JHARKHAND'),
    (68, 100, 'IN', 'KA', 'KARNATAKA'),
    (69, 100, 'IN', 'KL', 'KERALA'),
    (70, 100, 'IN', 'LD', 'LAKSHDWEEP'),
    (71, 100, 'IN', 'MP', 'MADHYA PRADESH'),
    (72, 100, 'IN', 'MH', 'MAHARASHTRA'),
    (73, 100, 'IN', 'MN', 'MANIPUR'),
    (74, 100, 'IN', 'MG', 'MEGHALAYA'),
    (75, 100, 'IN', 'MZ', 'MIZORAM'),
    (76, 100, 'IN', 'NG', 'NAGALAND'),
    (77, 100, 'IN', 'OR', 'ORISSA'),
    (78, 100, 'IN', 'PY', 'PONDICHERY'),
    (79, 100, 'IN', 'PB', 'PUNJAB'),
    (80, 100, 'IN', 'RN', 'RAJASTHAN'),
    (81, 100, 'IN', 'SK', 'SIKKIM'),
    (82, 100, 'IN', 'TN', 'TAMIL NADU'),
    (83, 100, 'IN', 'TP', 'TRIPURA'),
    (84, 100, 'IN', 'UP', 'UTTAR PRADESH'),
    (85, 100, 'IN', 'UT', 'UTTARANCHAL'),
    (86, 100, 'IN', 'WB', 'WEST BENGAL');
INSERT INTO master_cities (id, city, state_id)
VALUES (1, 'North and Middle Andaman', 32),
    (2, 'South Andaman', 32),
    (3, 'Nicobar', 32),
    (4, 'Adilabad', 1),
    (5, 'Anantapur', 1),
    (6, 'Chittoor', 1),
    (7, 'East Godavari', 1),
    (8, 'Guntur', 1),
    (9, 'Hyderabad', 1),
    (10, 'Kadapa', 1),
    (11, 'Karimnagar', 1),
    (12, 'Khammam', 1),
    (13, 'Krishna', 1),
    (14, 'Kurnool', 1),
    (15, 'Mahbubnagar', 1),
    (16, 'Medak', 1),
    (17, 'Nalgonda', 1),
    (18, 'Nellore', 1),
    (19, 'Nizamabad', 1),
    (20, 'Prakasam', 1),
    (21, 'Rangareddi', 1),
    (22, 'Srikakulam', 1),
    (23, 'Vishakhapatnam', 1),
    (24, 'Vizianagaram', 1),
    (25, 'Warangal', 1),
    (26, 'West Godavari', 1),
    (27, 'Anjaw', 3),
    (28, 'Changlang', 3),
    (29, 'East Kameng', 3),
    (30, 'Lohit', 3),
    (31, 'Lower Subansiri', 3),
    (32, 'Papum Pare', 3),
    (33, 'Tirap', 3),
    (34, 'Dibang Valley', 3),
    (35, 'Upper Subansiri', 3),
    (36, 'West Kameng', 3),
    (37, 'Barpeta', 2),
    (38, 'Bongaigaon', 2),
    (39, 'Cachar', 2),
    (40, 'Darrang', 2),
    (41, 'Dhemaji', 2),
    (42, 'Dhubri', 2),
    (43, 'Dibrugarh', 2),
    (44, 'Goalpara', 2),
    (45, 'Golaghat', 2),
    (46, 'Hailakandi', 2),
    (47, 'Jorhat', 2),
    (48, 'Karbi Anglong', 2),
    (49, 'Karimganj', 2),
    (50, 'Kokrajhar', 2),
    (51, 'Lakhimpur', 2),
    (52, 'Marigaon', 2),
    (53, 'Nagaon', 2),
    (54, 'Nalbari', 2),
    (55, 'North Cachar Hills', 2),
    (56, 'Sibsagar', 2),
    (57, 'Sonitpur', 2),
    (58, 'Tinsukia', 2),
    (59, 'Araria', 4),
    (60, 'Aurangabad', 4),
    (61, 'Banka', 4),
    (62, 'Begusarai', 4),
    (63, 'Bhagalpur', 4),
    (64, 'Bhojpur', 4),
    (65, 'Buxar', 4),
    (66, 'Darbhanga', 4),
    (67, 'Purba Champaran', 4),
    (68, 'Gaya', 4),
    (69, 'Gopalganj', 4),
    (70, 'Jamui', 4),
    (71, 'Jehanabad', 4),
    (72, 'Khagaria', 4),
    (73, 'Kishanganj', 4),
    (74, 'Kaimur', 4),
    (75, 'Katihar', 4),
    (76, 'Lakhisarai', 4),
    (77, 'Madhubani', 4),
    (78, 'Munger', 4),
    (79, 'Madhepura', 4),
    (80, 'Muzaffarpur', 4),
    (81, 'Nalanda', 4),
    (82, 'Nawada', 4),
    (83, 'Patna', 4),
    (84, 'Purnia', 4),
    (85, 'Rohtas', 4),
    (86, 'Saharsa', 4),
    (87, 'Samastipur', 4),
    (88, 'Sheohar', 4),
    (89, 'Sheikhpura', 4),
    (90, 'Saran', 4),
    (91, 'Sitamarhi', 4),
    (92, 'Supaul', 4),
    (93, 'Siwan', 4),
    (94, 'Vaishali', 4),
    (95, 'Pashchim Champaran', 4),
    (96, 'Bastar', 36),
    (97, 'Bilaspur', 36),
    (98, 'Dantewada', 36),
    (99, 'Dhamtari', 36),
    (100, 'Durg', 36),
    (101, 'Jashpur', 36),
    (102, 'Janjgir-Champa', 36),
    (103, 'Korba', 36),
    (104, 'Koriya', 36),
    (105, 'Kanker', 36),
    (106, 'Kawardha', 36),
    (107, 'Mahasamund', 36),
    (108, 'Raigarh', 36),
    (109, 'Rajnandgaon', 36),
    (110, 'Raipur', 36),
    (111, 'Surguja', 36),
    (112, 'Diu', 29),
    (113, 'Daman', 29),
    (114, 'Central Delhi', 25),
    (115, 'East Delhi', 25),
    (116, 'New Delhi', 25),
    (117, 'North Delhi', 25),
    (118, 'North East Delhi', 25),
    (119, 'North West Delhi', 25),
    (120, 'South Delhi', 25),
    (121, 'South West Delhi', 25),
    (122, 'West Delhi', 25),
    (123, 'North Goa', 26),
    (124, 'South Goa', 26),
    (125, 'Ahmedabad', 5),
    (126, 'Amreli District', 5),
    (127, 'Anand', 5),
    (128, 'Banaskantha', 5),
    (129, 'Bharuch', 5),
    (130, 'Bhavnagar', 5),
    (131, 'Dahod', 5),
    (132, 'The Dangs', 5),
    (133, 'Gandhinagar', 5),
    (134, 'Jamnagar', 5),
    (135, 'Junagadh', 5),
    (136, 'Kutch', 5),
    (137, 'Kheda', 5),
    (138, 'Mehsana', 5),
    (139, 'Narmada', 5),
    (140, 'Navsari', 5),
    (141, 'Patan', 5),
    (142, 'Panchmahal', 5),
    (143, 'Porbandar', 5),
    (144, 'Rajkot', 5),
    (145, 'Sabarkantha', 5),
    (146, 'Surendranagar', 5),
    (147, 'Surat', 5),
    (148, 'Vadodara', 5),
    (149, 'Valsad', 5),
    (150, 'Ambala', 6),
    (151, 'Bhiwani', 6),
    (152, 'Faridabad', 6),
    (153, 'Fatehabad', 6),
    (154, 'Gurgaon', 6),
    (155, 'Hissar', 6),
    (156, 'Jhajjar', 6),
    (157, 'Jind', 6),
    (158, 'Karnal', 6),
    (159, 'Kaithal', 6),
    (160, 'Kurukshetra', 6),
    (161, 'Mahendragarh', 6),
    (162, 'Mewat', 6),
    (163, 'Panchkula', 6),
    (164, 'Panipat', 6),
    (165, 'Rewari', 6),
    (166, 'Rohtak', 6),
    (167, 'Sirsa', 6),
    (168, 'Sonepat', 6),
    (169, 'Yamuna Nagar', 6),
    (170, 'Palwal', 6),
    (171, 'Bilaspur', 7),
    (172, 'Chamba', 7),
    (173, 'Hamirpur', 7),
    (174, 'Kangra', 7),
    (175, 'Kinnaur', 7),
    (176, 'Kulu', 7),
    (177, 'Lahaul and Spiti', 7),
    (178, 'Mandi', 7),
    (179, 'Shimla', 7),
    (180, 'Sirmaur', 7),
    (181, 'Solan', 7),
    (182, 'Una', 7),
    (183, 'Anantnag', 8),
    (184, 'Badgam', 8),
    (185, 'Bandipore', 8),
    (186, 'Baramula', 8),
    (187, 'Doda', 8),
    (188, 'Jammu', 8),
    (189, 'Kargil', 8),
    (190, 'Kathua', 8),
    (191, 'Kupwara', 8),
    (192, 'Leh', 8),
    (193, 'Poonch', 8),
    (194, 'Pulwama', 8),
    (195, 'Rajauri', 8),
    (196, 'Srinagar', 8),
    (197, 'Samba', 8),
    (198, 'Udhampur', 8),
    (199, 'Bokaro', 34),
    (200, 'Chatra', 34),
    (201, 'Deoghar', 34),
    (202, 'Dhanbad', 34),
    (203, 'Dumka', 34),
    (204, 'Purba Singhbhum', 34),
    (205, 'Garhwa', 34),
    (206, 'Giridih', 34),
    (207, 'Godda', 34),
    (208, 'Gumla', 34),
    (209, 'Hazaribagh', 34),
    (210, 'Koderma', 34),
    (211, 'Lohardaga', 34),
    (212, 'Pakur', 34),
    (213, 'Palamu', 34),
    (214, 'Ranchi', 34),
    (215, 'Sahibganj', 34),
    (216, 'Seraikela and Kharsawan', 34),
    (217, 'Pashchim Singhbhum', 34),
    (218, 'Ramgarh', 34),
    (219, 'Bidar', 9),
    (220, 'Belgaum', 9),
    (221, 'Bijapur', 9),
    (222, 'Bagalkot', 9),
    (223, 'Bellary', 9),
    (224, 'Bangalore Rural District', 9),
    (225, 'Bangalore Urban District', 9),
    (226, 'Chamarajnagar', 9),
    (227, 'Chikmagalur', 9),
    (228, 'Chitradurga', 9),
    (229, 'Davanagere', 9),
    (230, 'Dharwad', 9),
    (231, 'Dakshina Kannada', 9),
    (232, 'Gadag', 9),
    (233, 'Gulbarga', 9),
    (234, 'Hassan', 9),
    (235, 'Haveri District', 9),
    (236, 'Kodagu', 9),
    (237, 'Kolar', 9),
    (238, 'Koppal', 9),
    (239, 'Mandya', 9),
    (240, 'Mysore', 9),
    (241, 'Raichur', 9),
    (242, 'Shimoga', 9),
    (243, 'Tumkur', 9),
    (244, 'Udupi', 9),
    (245, 'Uttara Kannada', 9),
    (246, 'Ramanagara', 9),
    (247, 'Chikballapur', 9),
    (248, 'Yadagiri', 9),
    (249, 'Alappuzha', 10),
    (250, 'Ernakulam', 10),
    (251, 'Idukki', 10),
    (252, 'Kollam', 10),
    (253, 'Kannur', 10),
    (254, 'Kasaragod', 10),
    (255, 'Kottayam', 10),
    (256, 'Kozhikode', 10),
    (257, 'Malappuram', 10),
    (258, 'Palakkad', 10),
    (259, 'Pathanamthitta', 10),
    (260, 'Thrissur', 10),
    (261, 'Thiruvananthapuram', 10),
    (262, 'Wayanad', 10),
    (263, 'Alirajpur', 11),
    (264, 'Anuppur', 11),
    (265, 'Ashok Nagar', 11),
    (266, 'Balaghat', 11),
    (267, 'Barwani', 11),
    (268, 'Betul', 11),
    (269, 'Bhind', 11),
    (270, 'Bhopal', 11),
    (271, 'Burhanpur', 11),
    (272, 'Chhatarpur', 11),
    (273, 'Chhindwara', 11),
    (274, 'Damoh', 11),
    (275, 'Datia', 11),
    (276, 'Dewas', 11),
    (277, 'Dhar', 11),
    (278, 'Dindori', 11),
    (279, 'Guna', 11),
    (280, 'Gwalior', 11),
    (281, 'Harda', 11),
    (282, 'Hoshangabad', 11),
    (283, 'Indore', 11),
    (284, 'Jabalpur', 11),
    (285, 'Jhabua', 11),
    (286, 'Katni', 11),
    (287, 'Khandwa', 11),
    (288, 'Khargone', 11),
    (289, 'Mandla', 11),
    (290, 'Mandsaur', 11),
    (291, 'Morena', 11),
    (292, 'Narsinghpur', 11),
    (293, 'Neemuch', 11),
    (294, 'Panna', 11),
    (295, 'Rewa', 11),
    (296, 'Rajgarh', 11),
    (297, 'Ratlam', 11),
    (298, 'Raisen', 11),
    (299, 'Sagar', 11),
    (300, 'Satna', 11),
    (301, 'Sehore', 11),
    (302, 'Seoni', 11),
    (303, 'Shahdol', 11),
    (304, 'Shajapur', 11),
    (305, 'Sheopur', 11),
    (306, 'Shivpuri', 11),
    (307, 'Sidhi', 11),
    (308, 'Singrauli', 11),
    (309, 'Tikamgarh', 11),
    (310, 'Ujjain', 11),
    (311, 'Umaria', 11),
    (312, 'Vidisha', 11),
    (313, 'Ahmednagar', 12),
    (314, 'Akola', 12),
    (315, 'Amrawati', 12),
    (316, 'Aurangabad', 12),
    (317, 'Bhandara', 12),
    (318, 'Beed', 12),
    (319, 'Buldhana', 12),
    (320, 'Chandrapur', 12),
    (321, 'Dhule', 12),
    (322, 'Gadchiroli', 12),
    (323, 'Gondiya', 12),
    (324, 'Hingoli', 12),
    (325, 'Jalgaon', 12),
    (326, 'Jalna', 12),
    (327, 'Kolhapur', 12),
    (328, 'Latur', 12),
    (329, 'Mumbai City', 12),
    (330, 'Mumbai suburban', 12),
    (331, 'Nandurbar', 12),
    (332, 'Nanded', 12),
    (333, 'Nagpur', 12),
    (334, 'Nashik', 12),
    (335, 'Osmanabad', 12),
    (336, 'Parbhani', 12),
    (337, 'Pune', 12),
    (338, 'Raigad', 12),
    (339, 'Ratnagiri', 12),
    (340, 'Sindhudurg', 12),
    (341, 'Sangli', 12),
    (342, 'Solapur', 12),
    (343, 'Satara', 12),
    (344, 'Thane', 12),
    (345, 'Wardha', 12),
    (346, 'Washim', 12),
    (347, 'Yavatmal', 12),
    (348, 'Bishnupur', 13),
    (349, 'Churachandpur', 13),
    (350, 'Chandel', 13),
    (351, 'Imphal East', 13),
    (352, 'Senapati', 13),
    (353, 'Tamenglong', 13),
    (354, 'Thoubal', 13),
    (355, 'Ukhrul', 13),
    (356, 'Imphal West', 13),
    (357, 'East Garo Hills', 14),
    (358, 'East Khasi Hills', 14),
    (359, 'Jaintia Hills', 14),
    (360, 'Ri-Bhoi', 14),
    (361, 'South Garo Hills', 14),
    (362, 'West Garo Hills', 14),
    (363, 'West Khasi Hills', 14),
    (364, 'Aizawl', 15),
    (365, 'Champhai', 15),
    (366, 'Kolasib', 15),
    (367, 'Lawngtlai', 15),
    (368, 'Lunglei', 15),
    (369, 'Mamit', 15),
    (370, 'Saiha', 15),
    (371, 'Serchhip', 15),
    (372, 'Dimapur', 16),
    (373, 'Kohima', 16),
    (374, 'Mokokchung', 16),
    (375, 'Mon', 16),
    (376, 'Phek', 16),
    (377, 'Tuensang', 16),
    (378, 'Wokha', 16),
    (379, 'Zunheboto', 16),
    (380, 'Angul', 17),
    (381, 'Boudh', 17),
    (382, 'Bhadrak', 17),
    (383, 'Bolangir', 17),
    (384, 'Bargarh', 17),
    (385, 'Baleswar', 17),
    (386, 'Cuttack', 17),
    (387, 'Debagarh', 17),
    (388, 'Dhenkanal', 17),
    (389, 'Ganjam', 17),
    (390, 'Gajapati', 17),
    (391, 'Jharsuguda', 17),
    (392, 'Jajapur', 17),
    (393, 'Jagatsinghpur', 17),
    (394, 'Khordha', 17),
    (395, 'Kendujhar', 17),
    (396, 'Kalahandi', 17),
    (397, 'Kandhamal', 17),
    (398, 'Koraput', 17),
    (399, 'Kendrapara', 17),
    (400, 'Malkangiri', 17),
    (401, 'Mayurbhanj', 17),
    (402, 'Nabarangpur', 17),
    (403, 'Nuapada', 17),
    (404, 'Nayagarh', 17),
    (405, 'Puri', 17),
    (406, 'Rayagada', 17),
    (407, 'Sambalpur', 17),
    (408, 'Subarnapur', 17),
    (409, 'Sundargarh', 17),
    (410, 'Karaikal', 27),
    (411, 'Mahe', 27),
    (412, 'Puducherry', 27),
    (413, 'Yanam', 27),
    (414, 'Amritsar', 18),
    (415, 'Bathinda', 18),
    (416, 'Firozpur', 18),
    (417, 'Faridkot', 18),
    (418, 'Fatehgarh Sahib', 18),
    (419, 'Gurdaspur', 18),
    (420, 'Hoshiarpur', 18),
    (421, 'Jalandhar', 18),
    (422, 'Kapurthala', 18),
    (423, 'Ludhiana', 18),
    (424, 'Mansa', 18),
    (425, 'Moga', 18),
    (426, 'Mukatsar', 18),
    (427, 'Nawan Shehar', 18),
    (428, 'Patiala', 18),
    (429, 'Rupnagar', 18),
    (430, 'Sangrur', 18),
    (431, 'Ajmer', 19),
    (432, 'Alwar', 19),
    (433, 'Bikaner', 19),
    (434, 'Barmer', 19),
    (435, 'Banswara', 19),
    (436, 'Bharatpur', 19),
    (437, 'Baran', 19),
    (438, 'Bundi', 19),
    (439, 'Bhilwara', 19),
    (440, 'Churu', 19),
    (441, 'Chittorgarh', 19),
    (442, 'Dausa', 19),
    (443, 'Dholpur', 19),
    (444, 'Dungapur', 19),
    (445, 'Ganganagar', 19),
    (446, 'Hanumangarh', 19),
    (447, 'Juhnjhunun', 19),
    (448, 'Jalore', 19),
    (449, 'Jodhpur', 19),
    (450, 'Jaipur', 19),
    (451, 'Jaisalmer', 19),
    (452, 'Jhalawar', 19),
    (453, 'Karauli', 19),
    (454, 'Kota', 19),
    (455, 'Nagaur', 19),
    (456, 'Pali', 19),
    (457, 'Pratapgarh', 19),
    (458, 'Rajsamand', 19),
    (459, 'Sikar', 19),
    (460, 'Sawai Madhopur', 19),
    (461, 'Sirohi', 19),
    (462, 'Tonk', 19),
    (463, 'Udaipur', 19),
    (464, 'East Sikkim', 20),
    (465, 'North Sikkim', 20),
    (466, 'South Sikkim', 20),
    (467, 'West Sikkim', 20),
    (468, 'Ariyalur', 82),
    (469, 'Chennai', 82),
    (470, 'Coimbatore', 82),
    (471, 'Cuddalore', 82),
    (472, 'Dharmapuri', 82),
    (473, 'Dindigul', 82),
    (474, 'Erode', 82),
    (475, 'Kanchipuram', 82),
    (476, 'Kanyakumari', 82),
    (477, 'Karur', 82),
    (478, 'Madurai', 82),
    (479, 'Nagapattinam', 82),
    (480, 'The Nilgiris', 82),
    (481, 'Namakkal', 82),
    (482, 'Perambalur', 82),
    (483, 'Pudukkottai', 82),
    (484, 'Ramanathapuram', 82),
    (485, 'Salem', 82),
    (486, 'Sivagangai', 82),
    (487, 'Tiruppur', 82),
    (488, 'Tiruchirappalli', 82),
    (489, 'Theni', 82),
    (490, 'Tirunelveli', 82),
    (491, 'Thanjavur', 82),
    (492, 'Thoothukudi', 82),
    (493, 'Thiruvallur', 82),
    (494, 'Thiruvarur', 82),
    (495, 'Tiruvannamalai', 82),
    (496, 'Vellore', 82),
    (497, 'Villupuram', 82),
    (498, 'Dhalai', 22),
    (499, 'North Tripura', 22),
    (500, 'South Tripura', 22),
    (501, 'West Tripura', 22),
    (502, 'Almora', 33),
    (503, 'Bageshwar', 33),
    (504, 'Chamoli', 33),
    (505, 'Champawat', 33),
    (506, 'Dehradun', 33),
    (507, 'Haridwar', 33),
    (508, 'Nainital', 33),
    (509, 'Pauri Garhwal', 33),
    (510, 'Pithoragharh', 33),
    (511, 'Rudraprayag', 33),
    (512, 'Tehri Garhwal', 33),
    (513, 'Udham Singh Nagar', 33),
    (514, 'Uttarkashi', 33),
    (515, 'Agra', 23),
    (516, 'Allahabad', 23),
    (517, 'Aligarh', 23),
    (518, 'Ambedkar Nagar', 23),
    (519, 'Auraiya', 23),
    (520, 'Azamgarh', 23),
    (521, 'Barabanki', 23),
    (522, 'Badaun', 23),
    (523, 'Bagpat', 23),
    (524, 'Bahraich', 23),
    (525, 'Bijnor', 23),
    (526, 'Ballia', 23),
    (527, 'Banda', 23),
    (528, 'Balrampur', 23),
    (529, 'Bareilly', 23),
    (530, 'Basti', 23),
    (531, 'Bulandshahr', 23),
    (532, 'Chandauli', 23),
    (533, 'Chitrakoot', 23),
    (534, 'Deoria', 23),
    (535, 'Etah', 23),
    (536, 'Kanshiram Nagar', 23),
    (537, 'Etawah', 23),
    (538, 'Firozabad', 23),
    (539, 'Farrukhabad', 23),
    (540, 'Fatehpur', 23),
    (541, 'Faizabad', 23),
    (542, 'Gautam Buddha Nagar', 23),
    (543, 'Gonda', 23),
    (544, 'Ghazipur', 23),
    (545, 'Gorkakhpur', 23),
    (546, 'Ghaziabad', 23),
    (547, 'Hamirpur', 23),
    (548, 'Hardoi', 23),
    (549, 'Mahamaya Nagar', 23),
    (550, 'Jhansi', 23),
    (551, 'Jalaun', 23),
    (552, 'Jyotiba Phule Nagar', 23),
    (553, 'Jaunpur District', 23),
    (554, 'Kanpur Dehat', 23),
    (555, 'Kannauj', 23),
    (556, 'Kanpur Nagar', 23),
    (557, 'Kaushambi', 23),
    (558, 'Kushinagar', 23),
    (559, 'Lalitpur', 23),
    (560, 'Lakhimpur Kheri', 23),
    (561, 'Lucknow', 23),
    (562, 'Mau', 23),
    (563, 'Meerut', 23),
    (564, 'Maharajganj', 23),
    (565, 'Mahoba', 23),
    (566, 'Mirzapur', 23),
    (567, 'Moradabad', 23),
    (568, 'Mainpuri', 23),
    (569, 'Mathura', 23),
    (570, 'Muzaffarnagar', 23),
    (571, 'Pilibhit', 23),
    (572, 'Pratapgarh', 23),
    (573, 'Rampur', 23),
    (574, 'Rae Bareli', 23),
    (575, 'Saharanpur', 23),
    (576, 'Sitapur', 23),
    (577, 'Shahjahanpur', 23),
    (578, 'Sant Kabir Nagar', 23),
    (579, 'Siddharthnagar', 23),
    (580, 'Sonbhadra', 23),
    (581, 'Sant Ravidas Nagar', 23),
    (582, 'Sultanpur', 23),
    (583, 'Shravasti', 23),
    (584, 'Unnao', 23),
    (585, 'Varanasi', 23),
    (586, 'Birbhum', 24),
    (587, 'Bankura', 24),
    (588, 'Bardhaman', 24),
    (589, 'Darjeeling', 24),
    (590, 'Dakshin Dinajpur', 24),
    (591, 'Hooghly', 24),
    (592, 'Howrah', 24),
    (593, 'Jalpaiguri', 24),
    (594, 'Cooch Behar', 24),
    (595, 'Kolkata', 24),
    (596, 'Malda', 24),
    (597, 'Midnapore', 24),
    (598, 'Murshidabad', 24),
    (599, 'Nadia', 24),
    (600, 'North 24 Parganas', 24),
    (601, 'South 24 Parganas', 24),
    (602, 'Purulia', 24),
    (603, 'Uttar Dinajpur', 24);
CREATE TABLE IF NOT EXISTS organizations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code VARCHAR(25) UNIQUE NOT NULL,
    name VARCHAR(150) NOT NULL,
    registration_number VARCHAR(100) unique,
    website VARCHAR(255),
    address VARCHAR(500),
    country_id INTEGER,
    state_id INTEGER,
    city_id INTEGER,
    postal_code VARCHAR(20),
    primary_contact_name VARCHAR(150),
    primary_contact_email VARCHAR(150) unique,
    primary_contact_number VARCHAR(30) unique,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(country_id) REFERENCES master_countries(id),
    FOREIGN KEY(state_id) REFERENCES master_states(id),
    FOREIGN KEY(city_id) REFERENCES master_cities(id)
);
CREATE SEQUENCE organization_code_seq START 1 INCREMENT 1;
CREATE TABLE organization_settings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES organizations(id),
    logo_url VARCHAR(500),
    favicon_url VARCHAR(500),
    primary_color VARCHAR(20),
    timezone VARCHAR(100),
    currency VARCHAR(10),
    language VARCHAR(20),
    FOREIGN KEY (organization_id) REFERENCES organizations(id)
);
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES organizations(id),
    user_name VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) UNIQUE,
    contact_number varchar(30) UNIQUE,
    password VARCHAR(255) NULL,
    user_type VARCHAR(25),
    status VARCHAR(10) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS user_profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id),
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    gender varchar(20) NOT NULL,
    address VARCHAR(255),
    date_of_birth DATE,
    status VARCHAR(10),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(user_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS user_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    otp VARCHAR(255),
    otp_expiration TIMESTAMP,
    otp_verification_count INTEGER NOT NULL DEFAULT 0,
    is_otp_verified BOOLEAN NOT NULL DEFAULT FALSE,
    refresh_key VARCHAR(255),
    refresh_key_created_at TIMESTAMP,
    refresh_key_expiration TIMESTAMP,
    refresh_key_status BOOLEAN NOT NULL DEFAULT FALSE,
    is_valid_token BOOLEAN NOT NULL DEFAULT FALSE,
    session_status VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(user_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS user_verifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL UNIQUE,
    is_user_onboarded BOOLEAN DEFAULT FALSE,
    is_email_verified BOOLEAN DEFAULT FALSE,
    is_subscription_completed BOOLEAN DEFAULT FALSE,
    profile_completed_percentage INTEGER DEFAULT 0,
    is_password_reset_completed BOOLEAN DEFAULT false,
    failed_login_attempts INTEGER DEFAULT 0,
    is_account_locked BOOLEAN DEFAULT FALSE,
    locked_time TIMESTAMP,
    status VARCHAR(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_verifications_user FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS user_login_audit_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL,
    user_id UUID NOT NULL,
    logged_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    action VARCHAR(50),
    logged_ip VARCHAR(50),
    logged_browser VARCHAR(255),
    os_version VARCHAR(50),
    is_mobile BOOLEAN,
    attempted_username VARCHAR(100),
    attempted_password VARCHAR(250),
    returned_result VARCHAR(20)
);
CREATE TABLE IF NOT EXISTS password_resets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    otp VARCHAR(255),
    otp_expiration TIMESTAMP,
    otp_verification_count INTEGER DEFAULT 0,
    is_otp_verified BOOLEAN DEFAULT FALSE,
    reset_token varchar(255),
    reset_token_expiry TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(user_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS email_queue (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID,
    to_email VARCHAR(150) NOT NULL,
    body varchar(255),
    status VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    sent_at TIMESTAMP,
    FOREIGN KEY(user_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS member_categories (
    id SERIAL PRIMARY KEY,
    category VARCHAR(50) NOT NULL,
    description VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS locations (
    id serial PRIMARY KEY,
    location VARCHAR(50) NOT NULL,
    description varchar(255) null,
    created_at TIMESTAMP not null DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS members (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL,
    organization_code VARCHAR(25) NOT NULL,
    family_head_id UUID,
    category VARCHAR(30) not null,
    location varchar(30) not null,
    relation_ship varchar(50),
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    user_name VARCHAR(50) UNIQUE not null,
    gender VARCHAR(20) not null,
    wedding_Date date,
    date_of_birth DATE not null,
    date_of_join DATE not null,
    email VARCHAR(150) not null,
    contact_number VARCHAR(20) not null,
    address VARCHAR(255) not null,
    is_water_baptised boolean default false,
    is_spirit_baptised boolean default false,
    status VARCHAR(20),
    created_at TIMESTAMP not null DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(family_head_id) REFERENCES members(id),
    FOREIGN KEY(organization_id) REFERENCES organizations(id)
);
CREATE TABLE IF NOT EXISTS subscription_plans (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code VARCHAR(50) UNIQUE NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    price NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'INR',
    trial_days INTEGER DEFAULT 0,
    max_students INTEGER,
    max_teachers INTEGER,
    max_admins INTEGER,
    status varchar(10),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE subscription_features (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    status varchar(20)
);
CREATE SEQUENCE subscription_feature_code_seq START with 1 INCREMENT by 1;
CREATE TABLE subscription_plan_features (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    plan_id UUID NOT NULL,
    feature_id UUID NOT NULL,
    FOREIGN KEY (plan_id) REFERENCES subscription_plans(id) ON DELETE CASCADE,
    FOREIGN KEY (feature_id) REFERENCES subscription_features(id) ON DELETE CASCADE,
    CONSTRAINT uk_plan_feature UNIQUE(plan_id, feature_id)
);
CREATE TABLE subscription_organizations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL,
    plan_id UUID NOT NULL,
    billing_cycle varchar(20) not null,
    status VARCHAR(10) NOT NULL,
    start_date DATE NULL,
    end_date DATE,
    auto_renew BOOLEAN DEFAULT TRUE,
    cancelled_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (organization_id) REFERENCES organizations(id),
    FOREIGN KEY (plan_id) REFERENCES subscription_plans(id)
);
CREATE TABLE subscription_payments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    subscription_organization_id UUID NOT NULL,
    payment_type varchar(30) not null,
    amount NUMERIC(12, 2) NOT NULL,
    discount_percentage numeric(12, 2) not null,
    billing_amount numeric(12, 2) not null,
    currency VARCHAR(10) NOT NULL,
    payment_provider VARCHAR(50),
    payment_reference VARCHAR(255),
    transaction_id VARCHAR(255),
    status VARCHAR(30) NOT NULL,
    paid_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (subscription_organization_id) REFERENCES subscription_organizations(id)
);
CREATE TABLE subscription_usage (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    subscription_organization_id UUID NOT NULL UNIQUE,
    current_members INTEGER DEFAULT 0,
    current_teachers INTEGER DEFAULT 0,
    current_admins INTEGER DEFAULT 0,
    storage_used_mb BIGINT DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (subscription_organization_id) REFERENCES subscription_organizations(id)
);
CREATE TABLE subscription_audit_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL,
    old_plan_id UUID,
    new_plan_id UUID,
    action VARCHAR(50) NOT NULL,
    changed_by UUID,
    remarks TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (organization_id) REFERENCES organizations(id),
    FOREIGN KEY (old_plan_id) REFERENCES subscription_plans(id),
    FOREIGN KEY (new_plan_id) REFERENCES subscription_plans(id)
);
CREATE INDEX idx_subscription_organization ON subscription_organizations(organization_id);
CREATE INDEX idx_subscription_status ON subscription_organizations(status);
CREATE INDEX idx_payment_subscription ON subscription_payments(subscription_organization_id);
CREATE INDEX idx_subscription_usage_subscription ON subscription_usage(subscription_organization_id);
CREATE INDEX idx_audit_organization ON subscription_audit_logs(organization_id);
INSERT INTO subscription_plans (
        code,
        name,
        description,
        price,
        currency,
        trial_days,
        max_students,
        max_teachers,
        max_admins,
        status
    )
VALUES (
        'BASIC_PLAN',
        'Basic Plan',
        'Suitable for small churches and organizations.',
        999.00,
        'INR',
        15,
        500,
        50,
        5,
        'ACTIVE'
    ),
    (
        'STANDARD_PLAN',
        'Standard Plan',
        'Suitable for growing churches and organizations.',
        1999.00,
        'INR',
        15,
        1500,
        150,
        10,
        'ACTIVE'
    ),
    (
        'PREMIUM_PLAN',
        'Premium Plan',
        'Suitable for large churches and organizations.',
        3999.00,
        'INR',
        30,
        5000,
        500,
        25,
        'ACTIVE'
    );