server.port = 8080
server.servlet.context-path=/api
spring.application.name = accountmanagementsystem

spring.datasource.driver-class-name = org.postgresql.Driver
spring.datasource.url = jdbc:postgresql://localhost:5432/new_project
spring.datasource.username = postgres
spring.datasource.password = Tiger

spring.jpa.hibernate.ddl-auto = none
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

#authtoken config
authtoken.refreshkeyvalidity.days = 1
authtoken.tokenvalidity.seconds = 600
authtoken.signing.key = 3690db5849b44b9f86fb0254da4a627139f2e2ee7ea4de0dd6ae94552f542dc0f34ca4ae75d4ecdc263c43d425b1516703684a6023d3589452709bc7f19bc11b
authtoken.prefix = Bearer
authtoken.tokenname = Authorization
authtoken.issuer = 

#smtp config
spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.username = suriyasundar2021@gmail.com
spring.mail.password = spzc guyg dnav ukex
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true

spring.data.redis.host=localhost
spring.data.redis.port=6379




